### ISSUE TITLE
Is this package still alive?

### ISSUE THREAD

**Issue by iulianxpopa** [kunkaamd/google_sign_in_web_redirect#2]
Hello,

I'm trying to use Google Sign In as Redirect, not popup, since popups are blocked on many browsers.
I tried to use your package, but it's not working.

Is it still alive?

Thanks

**Comment by kunkaamd** [comment]
yes, so what is your issue, can you give me detail?

**Comment by iulianxpopa** [comment]
Tried to run the example using `flutter run -d chrome --web-hostname localhost --web-port 7357`, but I get this error

 *****I tried to use it with my own `google-signin-client_id` and auth route (`final response = await http.post(Uri.parse(.....))`), but I received the same error** 

<img width="348" alt="image" src="https://user-images.githubusercontent.com/38560810/197220876-0ac70504-fe9c-411a-b605-95c25d9e45e6.png">

**Comment by kunkaamd** [comment]
@iulianpopa1, I have just checked and it still working so please make sure you edit google-signin-client_id in web/index.html and update OAuth 2.0 Client IDs to look like that.
![Untitled](https://user-images.githubusercontent.com/22388256/197247564-abbc8919-322a-411b-a5fd-a72b08e7a1c8.png)
I also updated my example, so now you can check it again.

**Comment by kunkaamd** [comment]
it looks like you are using my `google-signin-client_id` key
