### ISSUE TITLE
Access token

### ISSUE THREAD

**Issue by amorenew** [kunkaamd/google_sign_in_web_redirect#3]
Hello,

After redirecting from google sign in, I only get id token and its data, I wonder how could I get access token so I can use it for firebase auth?
```
   final idToken = await GoogleSignWeb.instance!.token;

  final credential = GoogleAuthProvider.credential(
    accessToken:access_token,
    idToken: idToken,
  );

```

**Comment by amorenew** [comment]
accessToken is not required

**Comment by kunkaamd** [comment]
you should use responseType: "code". See the example. https://github.com/kunkaamd/google_sign_in_web_redirect/blob/884b8ef2393cdcac04ebda28d2bfe8c0bc0ef5db/example/lib/main.dart#L90

**Comment by amorenew** [comment]
@kunkaamd Thanks a lot I saw it in the readme
```
      GoogleSignWeb.init(
        ///id_token if you only want get user_id
        ///code if you need basic profile, access_token
        responseType: "code",
        scopes: ['email', 'profile'],
      );

```
